on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        aws sts get-caller-identity
        aws s3 ls --profile cst-test
        make build
    